services:
  # Backend API Service
  - type: web
    name: smart-dine-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: smart-dine-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://smart-dine-frontend.onrender.com
    
  # Frontend Static Site
  - type: web
    name: smart-dine-frontend
    runtime: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://smart-dine-backend.onrender.com/api

# Database
databases:
  - name: smart-dine-db
    databaseName: smartdine
    user: smartdine
    plan: free